In [1]:
import re

def camel_to_snake(name):
    # Insert an underscore between a lowercase/number and an uppercase letter
    name = re.sub(r'(.)([A-Z][a-z]+)', r'\1_\2', name)
    # Handle acronyms and standard camelCase transitions
    return re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', name).lower()

# Examples:
print(camel_to_snake('abcDef'))        # Output: abc_def
print(camel_to_snake('CamelCase'))     # Output: camel_case
print(camel_to_snake('HTTPResponse'))  # Output: http_response

abc_def
camel_case
http_response

In [1]:
import yfinance as yf
import pandas as pd

In [2]:
all_tickers = pd.read_json(r"C:\Users\zakis\OneDrive\Desktop\indonesia-stock-pipeline\data\indonesian_stock_list.json")

all_tickers.head()

,No,Kode,Nama Perusahaan,Tanggal Pencatatan,Saham,Papan Pencatatan
0,1,AALI,Astra Agro Lestari Tbk.,09 Des 1997,1.924.688.333,Utama
1,2,ABBA,Mahaka Media Tbk.,03 Apr 2002,3.935.892.857,Pemantauan Khusus
2,3,ABDA,Asuransi Bina Dana Arta Tbk.,06 Jul 1989,620.806.680,Pengembangan
3,4,ABMM,ABM Investama Tbk.,06 Des 2011,2.753.165.000,Utama
4,5,ACES,Aspirasi Hidup Indonesia Tbk.,06 Nov 2007,17.120.389.700,Utama

In [3]:
all_tickers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 957 entries, 0 to 956
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   No                  957 non-null    int64
 1   Kode                957 non-null    object
 2   Nama Perusahaan     957 non-null    object
 3   Tanggal Pencatatan  957 non-null    object
 4   Saham               957 non-null    object
 5   Papan Pencatatan    957 non-null    object
dtypes: int64(1), object(5)
memory usage: 45.0+ KB

In [4]:
all_tickers['Kode Jakarta'] = all_tickers['Kode'] + ".JK"

In [5]:
tickers_code = " ".join(all_tickers["Kode Jakarta"].tolist())
tickers_code

'AALI.JK ABBA.JK ABDA.JK ABMM.JK ACES.JK ACST.JK ADES.JK ADHI.JK AISA.JK AKKU.JK AKPI.JK AKRA.JK AKSI.JK ALDO.JK ALKA.JK ALMI.JK ALTO.JK AMAG.JK AMFG.JK AMIN.JK AMRT.JK ANJT.JK ANTM.JK APEX.JK APIC.JK APII.JK APLI.JK APLN.JK ARGO.JK ARII.JK ARNA.JK ARTA.JK ARTI.JK ARTO.JK ASBI.JK ASDM.JK ASGR.JK ASII.JK ASJT.JK ASMI.JK ASRI.JK ASRM.JK ASSA.JK ATIC.JK AUTO.JK BABP.JK BACA.JK BAJA.JK BALI.JK BAPA.JK BATA.JK BAYU.JK BBCA.JK BBHI.JK BBKP.JK BBLD.JK BBMD.JK BBNI.JK BBRI.JK BBRM.JK BBTN.JK BBYB.JK BCAP.JK BCIC.JK BCIP.JK BDMN.JK BEKS.JK BEST.JK BFIN.JK BGTG.JK BHIT.JK BIKA.JK BIMA.JK BINA.JK BIPI.JK BIPP.JK BIRD.JK BISI.JK BJBR.JK BJTM.JK BKDP.JK BKSL.JK BKSW.JK BLTA.JK BLTZ.JK BMAS.JK BMRI.JK BMSR.JK BMTR.JK BNBA.JK BNBR.JK BNGA.JK BNII.JK BNLI.JK BOLT.JK BPFI.JK BPII.JK BRAM.JK BRMS.JK BRNA.JK BRPT.JK BSDE.JK BSIM.JK BSSR.JK BSWD.JK BTEK.JK BTEL.JK BTON.JK BTPN.JK BUDI.JK BUKK.JK BULL.JK BUMI.JK BUVA.JK BVIC.JK BWPT.JK BYAN.JK CANI.JK CASS.JK CEKA.JK CENT.JK CFIN.JK CINT.JK CITA.JK CLPI.JK CMNP.JK CMPP.JK CNKO.JK CNTX.JK COWL.JK CPIN.JK CPRO.JK CSAP.JK CTBN.JK CTRA.JK CTTH.JK DART.JK DEFI.JK DEWA.JK DGIK.JK DILD.JK DKFT.JK DLTA.JK DMAS.JK DNAR.JK DNET.JK DOID.JK DPNS.JK DSFI.JK DSNG.JK DSSA.JK DUTI.JK DVLA.JK DYAN.JK ECII.JK EKAD.JK ELSA.JK ELTY.JK EMDE.JK EMTK.JK ENRG.JK EPMT.JK ERAA.JK ERTX.JK ESSA.JK ESTI.JK ETWA.JK EXCL.JK FAST.JK FASW.JK FISH.JK FMII.JK FORU.JK FPNI.JK GAMA.JK GDST.JK GDYR.JK GEMA.JK GEMS.JK GGRM.JK GIAA.JK GJTL.JK GLOB.JK GMTD.JK GOLD.JK GOLL.JK GPRA.JK GSMF.JK GTBO.JK GWSA.JK GZCO.JK HADE.JK HDFA.JK HERO.JK HEXA.JK HITS.JK HMSP.JK HOME.JK HOTL.JK HRUM.JK IATA.JK IBFN.JK IBST.JK ICBP.JK ICON.JK IGAR.JK IIKP.JK IKAI.JK IKBI.JK IMAS.JK IMJS.JK IMPC.JK INAF.JK INAI.JK INCI.JK INCO.JK INDF.JK INDR.JK INDS.JK INDX.JK INDY.JK INKP.JK INPC.JK INPP.JK INRU.JK INTA.JK INTD.JK INTP.JK IPOL.JK ISAT.JK ISSP.JK ITMA.JK ITMG.JK JAWA.JK JECC.JK JIHD.JK JKON.JK JPFA.JK JRPT.JK JSMR.JK JSPT.JK JTPE.JK KAEF.JK KARW.JK KBLI.JK KBLM.JK KBLV.JK KBRI.JK KDSI.JK KIAS.JK KICI.JK KIJA.JK KKGI.JK KLBF.JK KOBX.JK KOIN.JK KONI.JK KOPI.JK KPIG.JK KRAS.JK KREN.JK LAPD.JK LCGP.JK LEAD.JK LINK.JK LION.JK LMAS.JK LMPI.JK LMSH.JK LPCK.JK LPGI.JK LPIN.JK LPKR.JK LPLI.JK LPPF.JK LPPS.JK LRNA.JK LSIP.JK LTLS.JK MAGP.JK MAIN.JK MAPI.JK MAYA.JK MBAP.JK MBSS.JK MBTO.JK MCOR.JK MDIA.JK MDKA.JK MDLN.JK MDRN.JK MEDC.JK MEGA.JK MERK.JK META.JK MFMI.JK MGNA.JK MICE.JK MIDI.JK MIKA.JK MIRA.JK MITI.JK MKPI.JK MLBI.JK MLIA.JK MLPL.JK MLPT.JK MMLP.JK MNCN.JK MPMX.JK MPPA.JK MRAT.JK MREI.JK MSKY.JK MTDL.JK MTFN.JK MTLA.JK MTSM.JK MYOH.JK MYOR.JK MYTX.JK NELY.JK NIKL.JK NIRO.JK NISP.JK NOBU.JK NRCA.JK OCAP.JK OKAS.JK OMRE.JK PADI.JK PALM.JK PANR.JK PANS.JK PBRX.JK PDES.JK PEGE.JK PGAS.JK PGLI.JK PICO.JK PJAA.JK PKPK.JK PLAS.JK PLIN.JK PNBN.JK PNBS.JK PNIN.JK PNLF.JK PSAB.JK PSDN.JK PSKT.JK PTBA.JK PTIS.JK PTPP.JK PTRO.JK PTSN.JK PTSP.JK PUDP.JK PWON.JK PYFA.JK RAJA.JK RALS.JK RANC.JK RBMS.JK RDTX.JK RELI.JK RICY.JK RIGS.JK RIMO.JK RODA.JK ROTI.JK RUIS.JK SAFE.JK SAME.JK SCCO.JK SCMA.JK SCPI.JK SDMU.JK SDPC.JK SDRA.JK SGRO.JK SHID.JK SIDO.JK SILO.JK SIMA.JK SIMP.JK SIPD.JK SKBM.JK SKLT.JK SKYB.JK SMAR.JK SMBR.JK SMCB.JK SMDM.JK SMDR.JK SMGR.JK SMMA.JK SMMT.JK SMRA.JK SMRU.JK SMSM.JK SOCI.JK SONA.JK SPMA.JK SQMI.JK SRAJ.JK SRIL.JK SRSN.JK SRTG.JK SSIA.JK SSMS.JK SSTM.JK STAR.JK STTP.JK SUGI.JK SULI.JK SUPR.JK TALF.JK TARA.JK TAXI.JK TBIG.JK TBLA.JK TBMS.JK TCID.JK TELE.JK TFCO.JK TGKA.JK TIFA.JK TINS.JK TIRA.JK TIRT.JK TKIM.JK TLKM.JK TMAS.JK TMPO.JK TOBA.JK TOTL.JK TOTO.JK TOWR.JK TPIA.JK TPMA.JK TRAM.JK TRIL.JK TRIM.JK TRIO.JK TRIS.JK TRST.JK TRUS.JK TSPC.JK ULTJ.JK UNIC.JK UNIT.JK UNSP.JK UNTR.JK UNVR.JK VICO.JK VINS.JK VIVA.JK VOKS.JK VRNA.JK WAPO.JK WEHA.JK WICO.JK WIIM.JK WIKA.JK WINS.JK WOMF.JK WSKT.JK WTON.JK YPAS.JK YULE.JK ZBRA.JK SHIP.JK CASA.JK DAYA.JK DPUM.JK IDPR.JK JGLE.JK KINO.JK MARI.JK MKNT.JK MTRA.JK OASA.JK POWR.JK INCF.JK WSBP.JK PBSA.JK PRDA.JK BOGA.JK BRIS.JK PORT.JK CARS.JK MINA.JK CLEO.JK TAMU.JK CSIS.JK TGRA.JK FIRE.JK TOPS.JK KMTR.JK ARMY.JK MAPB.JK WOOD.JK HRTA.JK MABA.JK HOKI.JK MPOW.JK MARK.JK NASA.JK MDKI.JK BELL.JK KIOS.JK GMFI.JK MTWI.JK ZINC.JK MCAS.JK PPRE.JK WEGE.JK PSSI.JK MORA.JK DWGL.JK PBID.JK JMAS.JK CAMP.JK IPCM.JK PCAR.JK LCKM.JK BOSS.JK HELI.JK JSKY.JK INPS.JK GHON.JK TDPM.JK DFAM.JK NICK.JK BTPS.JK SPTO.JK PRIM.JK HEAL.JK TRUK.JK PZZA.JK TUGU.JK MSIN.JK SWAT.JK TNCA.JK MAPA.JK TCPI.JK IPCC.JK RISE.JK BPTR.JK POLL.JK NFCX.JK MGRO.JK NUSA.JK FILM.JK ANDI.JK LAND.JK MOLI.JK PANI.JK DIGI.JK CITY.JK SAPX.JK SURE.JK HKMU.JK MPRO.JK DUCK.JK GOOD.JK SKRN.JK YELO.JK CAKK.JK SATU.JK SOSS.JK DEAL.JK POLA.JK DIVA.JK LUCK.JK URBN.JK SOTS.JK ZONE.JK PEHA.JK FOOD.JK BEEF.JK POLI.JK CLAY.JK NATO.JK JAYA.JK COCO.JK MTPS.JK CPRI.JK HRME.JK POSA.JK JAST.JK FITT.JK BOLA.JK CCSI.JK SFAN.JK POLU.JK KJEN.JK KAYU.JK ITIC.JK PAMG.JK IPTV.JK BLUE.JK ENVY.JK EAST.JK LIFE.JK FUJI.JK KOTA.JK INOV.JK ARKA.JK SMKL.JK HDIT.JK KEEN.JK BAPI.JK TFAS.JK GGRP.JK OPMS.JK NZIA.JK SLIS.JK PURE.JK IRRA.JK DMMX.JK SINI.JK WOWS.JK ESIP.JK TEBE.JK KEJU.JK PSGO.JK AGAR.JK IFSH.JK REAL.JK IFII.JK PMJS.JK UCID.JK GLVA.JK PGJO.JK AMAR.JK CSRA.JK INDO.JK AMOR.JK TRIN.JK DMND.JK PURA.JK PTPW.JK TAMA.JK IKAN.JK SAMF.JK SBAT.JK KBAG.JK CBMF.JK RONY.JK CSMI.JK BBSS.JK BHAT.JK CASH.JK TECH.JK EPAC.JK UANG.JK PGUN.JK SOFA.JK PPGL.JK TOYS.JK SGER.JK TRJA.JK PNGO.JK SCNP.JK BBSI.JK KMDS.JK PURI.JK SOHO.JK HOMI.JK ROCK.JK ENZO.JK PLAN.JK PTDU.JK ATAP.JK VICI.JK PMMP.JK BANK.JK WMUU.JK EDGE.JK UNIQ.JK BEBS.JK SNLK.JK ZYRX.JK LFLO.JK FIMP.JK TAPG.JK NPGF.JK LUCY.JK ADCP.JK HOPE.JK MGLV.JK TRUE.JK LABA.JK ARCI.JK IPAC.JK MASB.JK BMHS.JK FLMC.JK NICL.JK UVCR.JK BUKA.JK HAIS.JK OILS.JK GPSO.JK MCOL.JK RSGK.JK RUNS.JK SBMA.JK CMNT.JK GTSI.JK IDEA.JK KUAS.JK BOBA.JK MTEL.JK DEPO.JK BINO.JK CMRY.JK WGSH.JK TAYS.JK WMPP.JK RMKE.JK OBMD.JK AVIA.JK IPPE.JK NASI.JK BSML.JK DRMA.JK ADMR.JK SEMA.JK ASLC.JK NETV.JK BAUT.JK ENAK.JK NTBK.JK SMKM.JK STAA.JK NANO.JK BIKE.JK WIRG.JK SICO.JK GOTO.JK TLDN.JK MTMH.JK WINR.JK IBOS.JK OLIV.JK ASHA.JK SWID.JK TRGU.JK ARKO.JK CHEM.JK DEWI.JK AXIO.JK KRYA.JK HATM.JK RCCC.JK GULA.JK JARR.JK AMMS.JK RAFI.JK KKES.JK ELPI.JK EURO.JK KLIN.JK TOOL.JK BUAH.JK CRAB.JK MEDS.JK COAL.JK PRAY.JK CBUT.JK BELI.JK MKTR.JK OMED.JK BSBK.JK PDPP.JK KDTN.JK ZATA.JK NINE.JK MMIX.JK PADA.JK ISAP.JK VTNY.JK SOUL.JK ELIT.JK BEER.JK CBPE.JK SUNI.JK CBRE.JK WINE.JK BMBL.JK PEVE.JK LAJU.JK FWCT.JK NAYZ.JK IRSX.JK PACK.JK VAST.JK CHIP.JK HALO.JK KING.JK PGEO.JK FUTR.JK HILL.JK BDKR.JK PTMP.JK SAGE.JK TRON.JK CUAN.JK NSSS.JK GTRA.JK HAJJ.JK JATI.JK TYRE.JK MPXL.JK SMIL.JK KLAS.JK MAXI.JK VKTR.JK RELF.JK AMMN.JK CRSN.JK GRPM.JK WIDI.JK TGUK.JK INET.JK MAHA.JK RMKO.JK CNMA.JK FOLK.JK HBAT.JK GRIA.JK PPRI.JK ERAL.JK CYBR.JK MUTU.JK LMAX.JK HUMI.JK MSIE.JK RSCH.JK BABY.JK AEGS.JK IOTF.JK KOCI.JK PTPS.JK BREN.JK STRK.JK KOKA.JK LOPI.JK UDNG.JK RGAS.JK MSTI.JK IKPM.JK AYAM.JK SURI.JK ASLI.JK GRPH.JK SMGA.JK UNTD.JK TOSK.JK MPIX.JK ALII.JK MKAP.JK MEJA.JK LIVE.JK HYGN.JK BAIK.JK VISI.JK AREA.JK MHKI.JK ATLA.JK DATA.JK SOLA.JK BATR.JK SPRE.JK PART.JK GOLF.JK ISEA.JK BLES.JK GUNA.JK LABS.JK DOSS.JK NEST.JK PTMR.JK VERN.JK DAAZ.JK BOAT.JK NAIK.JK AADI.JK MDIY.JK KSIX.JK RATU.JK YOII.JK HGII.JK BRRC.JK DGWG.JK CBDK.JK OBAT.JK MINE.JK ASPR.JK PSAT.JK COIN.JK CDIA.JK BLOG.JK MERI.JK KAQI.JK YUPI.JK FORE.JK MDLA.JK DKHH.JK AYLS.JK DADA.JK ASPI.JK ESTA.JK BESS.JK AMAN.JK CARE.JK PIPA.JK NCKL.JK MENN.JK AWAN.JK MBMA.JK RAAM.JK DOOH.JK CGAS.JK NICE.JK MSJA.JK SMLE.JK ACRO.JK MANG.JK WIFI.JK FAPA.JK DCII.JK KETR.JK DGNS.JK UFOE.JK CHEK.JK PMUI.JK EMAS.JK PJHB.JK RLCO.JK SUPA.JK WBSA.JK ADMF.JK ADMG.JK ADRO.JK AGII.JK AGRO.JK AGRS.JK AHAP.JK AIMS.JK PNSE.JK POLY.JK POOL.JK PPRO.JK'

# Metadata

In [40]:
target_tickers = yf.Tickers(tickers_code)
metadata_list = []

# Loop through the dictionary of Ticker objects
for symbol, ticker in target_tickers.tickers.items():
    info = ticker.info
    metadata_list.append({
        "ticker": symbol,
        **info
    })
    break

# Convert to a DataFrame for easy viewing
df = pd.DataFrame(metadata_list)
display(df)

,ticker,address1,address2,city,zip,country,phone,fax,website,industry,...,gmtOffSetMilliseconds,market,esgPopulated,regularMarketChangePercent,shortName,longName,regularMarketPrice,marketState,cryptoTradeable,trailingPegRatio
0,AALI.JK,JI. Pulo Ayang Raya Blok OR-1,Kawasan Industri Pulogadung Jakarta Timur,Jakarta,13930,Indonesia,62 21 461 6555,62 21 461 6685,https://www.astra-agro.co.id,Farm Products,...,25200000,id_market,False,1.612903,Astra Agro Lestari Tbk.,PT Astra Agro Lestari Tbk,6300.0,REGULAR,False,0.9393

In [41]:
print(df.columns.to_list())

['ticker', 'address1', 'address2', 'city', 'zip', 'country', 'phone', 'fax', 'website', 'industry', 'industryKey', 'industryDisp', 'sector', 'sectorKey', 'sectorDisp', 'longBusinessSummary', 'fullTimeEmployees', 'companyOfficers', 'executiveTeam', 'maxAge', 'priceHint', 'previousClose', 'open', 'dayLow', 'dayHigh', 'regularMarketPreviousClose', 'regularMarketOpen', 'regularMarketDayLow', 'regularMarketDayHigh', 'dividendRate', 'dividendYield', 'exDividendDate', 'payoutRatio', 'fiveYearAvgDividendYield', 'beta', 'trailingPE', 'forwardPE', 'volume', 'regularMarketVolume', 'averageVolume', 'averageVolume10days', 'averageDailyVolume10Day', 'bid', 'ask', 'bidSize', 'askSize', 'marketCap', 'nonDilutedMarketCap', 'fiftyTwoWeekLow', 'fiftyTwoWeekHigh', 'allTimeHigh', 'allTimeLow', 'priceToSalesTrailing12Months', 'fiftyDayAverage', 'twoHundredDayAverage', 'trailingAnnualDividendRate', 'trailingAnnualDividendYield', 'currency', 'tradeable', 'enterpriseValue', 'profitMargins', 'floatShares', 'sharesOutstanding', 'heldPercentInsiders', 'heldPercentInstitutions', 'impliedSharesOutstanding', 'bookValue', 'priceToBook', 'lastFiscalYearEnd', 'nextFiscalYearEnd', 'mostRecentQuarter', 'earningsQuarterlyGrowth', 'netIncomeToCommon', 'trailingEps', 'forwardEps', 'pegRatio', 'enterpriseToRevenue', 'enterpriseToEbitda', '52WeekChange', 'SandP52WeekChange', 'lastDividendValue', 'lastDividendDate', 'quoteType', 'currentPrice', 'targetHighPrice', 'targetLowPrice', 'targetMeanPrice', 'targetMedianPrice', 'recommendationMean', 'recommendationKey', 'numberOfAnalystOpinions', 'totalCash', 'totalCashPerShare', 'ebitda', 'totalDebt', 'quickRatio', 'currentRatio', 'totalRevenue', 'revenuePerShare', 'returnOnAssets', 'returnOnEquity', 'grossProfits', 'freeCashflow', 'operatingCashflow', 'earningsGrowth', 'revenueGrowth', 'grossMargins', 'ebitdaMargins', 'operatingMargins', 'financialCurrency', 'symbol', 'language', 'region', 'typeDisp', 'quoteSourceName', 'triggerable', 'customPriceAlertConfidence', 'averageDailyVolume3Month', 'fiftyTwoWeekLowChange', 'fiftyTwoWeekLowChangePercent', 'fiftyTwoWeekRange', 'fiftyTwoWeekHighChange', 'fiftyTwoWeekHighChangePercent', 'fiftyTwoWeekChangePercent', 'earningsTimestampStart', 'earningsTimestampEnd', 'isEarningsDateEstimate', 'epsTrailingTwelveMonths', 'epsForward', 'epsCurrentYear', 'priceEpsCurrentYear', 'fiftyDayAverageChange', 'fiftyDayAverageChangePercent', 'twoHundredDayAverageChange', 'twoHundredDayAverageChangePercent', 'sourceInterval', 'exchangeDataDelayedBy', 'averageAnalystRating', 'hasPrePostMarketData', 'firstTradeDateMilliseconds', 'regularMarketChange', 'regularMarketDayRange', 'fullExchangeName', 'corporateActions', 'regularMarketTime', 'exchange', 'messageBoardId', 'exchangeTimezoneName', 'exchangeTimezoneShortName', 'gmtOffSetMilliseconds', 'market', 'esgPopulated', 'regularMarketChangePercent', 'shortName', 'longName', 'regularMarketPrice', 'marketState', 'cryptoTradeable', 'trailingPegRatio']

In [42]:
display(df)

,ticker,address1,address2,city,zip,country,phone,fax,website,industry,...,gmtOffSetMilliseconds,market,esgPopulated,regularMarketChangePercent,shortName,longName,regularMarketPrice,marketState,cryptoTradeable,trailingPegRatio
0,AALI.JK,JI. Pulo Ayang Raya Blok OR-1,Kawasan Industri Pulogadung Jakarta Timur,Jakarta,13930,Indonesia,62 21 461 6555,62 21 461 6685,https://www.astra-agro.co.id,Farm Products,...,25200000,id_market,False,1.612903,Astra Agro Lestari Tbk.,PT Astra Agro Lestari Tbk,6300.0,REGULAR,False,0.9393

In [43]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 159 columns):
 #    Column                             Dtype
---   ------                             -----
 0    ticker                             object
 1    address1                           object
 2    address2                           object
 3    city                               object
 4    zip                                object
 5    country                            object
 6    phone                              object
 7    fax                                object
 8    website                            object
 9    industry                           object
 10   industryKey                        object
 11   industryDisp                       object
 12   sector                             object
 13   sectorKey                          object
 14   sectorDisp                         object
 15   longBusinessSummary                object
 16   fullTimeEmployees                  int64
 17   companyOfficers                    object
 18   executiveTeam                      object
 19   maxAge                             int64
 20   priceHint                          int64
 21   previousClose                      float64
 22   open                               float64
 23   dayLow                             float64
 24   dayHigh                            float64
 25   regularMarketPreviousClose         float64
 26   regularMarketOpen                  float64
 27   regularMarketDayLow                float64
 28   regularMarketDayHigh               float64
 29   dividendRate                       float64
 30   dividendYield                      float64
 31   exDividendDate                     int64
 32   payoutRatio                        float64
 33   fiveYearAvgDividendYield           float64
 34   beta                               float64
 35   trailingPE                         float64
 36   forwardPE                          float64
 37   volume                             int64
 38   regularMarketVolume                int64
 39   averageVolume                      int64
 40   averageVolume10days                int64
 41   averageDailyVolume10Day            int64
 42   bid                                float64
 43   ask                                float64
 44   bidSize                            int64
 45   askSize                            int64
 46   marketCap                          int64
 47   nonDilutedMarketCap                int64
 48   fiftyTwoWeekLow                    float64
 49   fiftyTwoWeekHigh                   float64
 50   allTimeHigh                        float64
 51   allTimeLow                         float64
 52   priceToSalesTrailing12Months       float64
 53   fiftyDayAverage                    float64
 54   twoHundredDayAverage               float64
 55   trailingAnnualDividendRate         float64
 56   trailingAnnualDividendYield        float64
 57   currency                           object
 58   tradeable                          bool
 59   enterpriseValue                    int64
 60   profitMargins                      float64
 61   floatShares                        int64
 62   sharesOutstanding                  int64
 63   heldPercentInsiders                float64
 64   heldPercentInstitutions            float64
 65   impliedSharesOutstanding           int64
 66   bookValue                          float64
 67   priceToBook                        float64
 68   lastFiscalYearEnd                  int64
 69   nextFiscalYearEnd                  int64
 70   mostRecentQuarter                  int64
 71   earningsQuarterlyGrowth            float64
 72   netIncomeToCommon                  int64
 73   trailingEps                        float64
 74   forwardEps                         float64
 75   pegRatio                           float64
 76   enterpriseToRevenue                float64
 77   enterpriseToEbitda                 float64
 78   52WeekChange                       float64
 79   SandP52WeekChange                  float64
 80   lastDividendValue                  float64
 81   lastDividendDate                   int64
 82   quoteType                          object
 83   currentPrice                       float64
 84   targetHighPrice                    float64
 85   targetLowPrice                     float64
 86   targetMeanPrice                    float64
 87   targetMedianPrice                  float64
 88   recommendationMean                 float64
 89   recommendationKey                  object
 90   numberOfAnalystOpinions            int64
 91   totalCash                          int64
 92   totalCashPerShare                  float64
 93   ebitda                             int64
 94   totalDebt                          int64
 95   quickRatio                         float64
 96   currentRatio                       float64
 97   totalRevenue                       int64
 98   revenuePerShare                    float64
 99   returnOnAssets                     float64
 100  returnOnEquity                     float64
 101  grossProfits                       int64
 102  freeCashflow                       int64
 103  operatingCashflow                  int64
 104  earningsGrowth                     float64
 105  revenueGrowth                      float64
 106  grossMargins                       float64
 107  ebitdaMargins                      float64
 108  operatingMargins                   float64
 109  financialCurrency                  object
 110  symbol                             object
 111  language                           object
 112  region                             object
 113  typeDisp                           object
 114  quoteSourceName                    object
 115  triggerable                        bool
 116  customPriceAlertConfidence         object
 117  averageDailyVolume3Month           int64
 118  fiftyTwoWeekLowChange              float64
 119  fiftyTwoWeekLowChangePercent       float64
 120  fiftyTwoWeekRange                  object
 121  fiftyTwoWeekHighChange             float64
 122  fiftyTwoWeekHighChangePercent      float64
 123  fiftyTwoWeekChangePercent          float64
 124  earningsTimestampStart             int64
 125  earningsTimestampEnd               int64
 126  isEarningsDateEstimate             bool
 127  epsTrailingTwelveMonths            float64
 128  epsForward                         float64
 129  epsCurrentYear                     float64
 130  priceEpsCurrentYear                float64
 131  fiftyDayAverageChange              float64
 132  fiftyDayAverageChangePercent       float64
 133  twoHundredDayAverageChange         float64
 134  twoHundredDayAverageChangePercent  float64
 135  sourceInterval                     int64
 136  exchangeDataDelayedBy              int64
 137  averageAnalystRating               object
 138  hasPrePostMarketData               bool
 139  firstTradeDateMilliseconds         int64
 140  regularMarketChange                float64
 141  regularMarketDayRange              object
 142  fullExchangeName                   object
 143  corporateActions                   object
 144  regularMarketTime                  int64
 145  exchange                           object
 146  messageBoardId                     object
 147  exchangeTimezoneName               object
 148  exchangeTimezoneShortName          object
 149  gmtOffSetMilliseconds              int64
 150  market                             object
 151  esgPopulated                       bool
 152  regularMarketChangePercent         float64
 153  shortName                          object
 154  longName                           object
 155  regularMarketPrice                 float64
 156  marketState                        object
 157  cryptoTradeable                    bool
 158  trailingPegRatio                   float64
dtypes: bool(6), float64(74), int64(38), object(41)
memory usage: 1.3+ KB

In [45]:
# 1. Define column groups based on the yfinance schema
METADATA_COLS = [
    'ticker', 'symbol', 'longName', 'shortName', 'exchange', 'fullExchangeName', 
    'market', 'sector', 'sectorKey', 'sectorDisp', 'industry', 'industryKey', 
    'industryDisp', 'longBusinessSummary', 'fullTimeEmployees', 'companyOfficers', 
    'executiveTeam', 'address1', 'address2', 'city', 'zip', 'country', 'phone', 
    'fax', 'website', 'currency', 'financialCurrency', 'language', 'region', 
    'quoteType', 'typeDisp', 'messageBoardId', 'exchangeTimezoneName', 
    'exchangeTimezoneShortName', 'gmtOffSetMilliseconds'
]

MARKET_DATA_COLS = [
    'currentPrice', 'previousClose', 'open', 'dayLow', 'dayHigh', 
    'regularMarketPreviousClose', 'regularMarketOpen', 'regularMarketDayLow', 
    'regularMarketDayHigh', 'regularMarketPrice', 'regularMarketChange', 
    'regularMarketChangePercent', 'volume', 'regularMarketVolume', 'averageVolume', 
    'averageVolume10days', 'averageDailyVolume10Day', 'averageDailyVolume3Month', 
    'bid', 'ask', 'bidSize', 'askSize', 'marketState', 'regularMarketTime', 
    'fiftyTwoWeekLow', 'fiftyTwoWeekHigh', 'allTimeHigh', 'allTimeLow', 
    'fiftyDayAverage', 'twoHundredDayAverage', '52WeekChange', 'SandP52WeekChange', 
    'fiftyTwoWeekLowChange', 'fiftyTwoWeekLowChangePercent', 'fiftyTwoWeekRange', 
    'fiftyTwoWeekHighChange', 'fiftyTwoWeekHighChangePercent', 'fiftyTwoWeekChangePercent', 
    'fiftyDayAverageChange', 'fiftyDayAverageChangePercent', 'twoHundredDayAverageChange', 
    'twoHundredDayAverageChangePercent', 'tradeable', 'triggerable', 'cryptoTradeable', 
    'hasPrePostMarketData', 'firstTradeDateMilliseconds', 'regularMarketDayRange'
]

FUNDAMENTAL_COLS = [
    'marketCap', 'nonDilutedMarketCap', 'enterpriseValue', 'profitMargins', 
    'floatShares', 'sharesOutstanding', 'impliedSharesOutstanding', 'bookValue', 
    'priceToBook', 'trailingPE', 'forwardPE', 'priceToSalesTrailing12Months', 
    'netIncomeToCommon', 'trailingEps', 'forwardEps', 'pegRatio', 'trailingPegRatio', 
    'enterpriseToRevenue', 'enterpriseToEbitda', 'totalCash', 'totalCashPerShare', 
    'ebitda', 'totalDebt', 'quickRatio', 'currentRatio', 'totalRevenue', 
    'revenuePerShare', 'returnOnAssets', 'returnOnEquity', 'grossProfits', 
    'freeCashflow', 'operatingCashflow', 'earningsGrowth', 'revenueGrowth', 
    'grossMargins', 'ebitdaMargins', 'operatingMargins', 'epsTrailingTwelveMonths', 
    'epsForward', 'epsCurrentYear', 'priceEpsCurrentYear', 'heldPercentInsiders', 
    'heldPercentInstitutions', 'lastFiscalYearEnd', 'nextFiscalYearEnd', 'mostRecentQuarter',
    'dividendRate', 'dividendYield', 'exDividendDate', 'payoutRatio', 
    'fiveYearAvgDividendYield', 'trailingAnnualDividendRate', 'trailingAnnualDividendYield', 
    'lastDividendValue', 'lastDividendDate', 'corporateActions'
]

ANALYST_COLS = [
    'targetHighPrice', 'targetLowPrice', 'targetMeanPrice', 'targetMedianPrice', 
    'recommendationMean', 'recommendationKey', 'numberOfAnalystOpinions', 
    'averageAnalystRating', 'earningsTimestampStart', 'earningsTimestampEnd', 
    'isEarningsDateEstimate'
]

# 2. Safely extract existing columns from your DataFrame
# (Using intersection avoids KeyErrors if certain tickers miss some fields)
df_metadata = df[df.columns.intersection(METADATA_COLS)]
df_market   = df[df.columns.intersection(MARKET_DATA_COLS)]
df_fundamentals = df[df.columns.intersection(FUNDAMENTAL_COLS)]
df_analysts  = df[df.columns.intersection(ANALYST_COLS)]

# 3. Check the split structures
print("Metadata shape:", df_metadata.shape)
print("Market Data shape:", df_market.shape)
print("Fundamentals shape:", df_fundamentals.shape)

Metadata shape: (1, 35)
Market Data shape: (1, 48)
Fundamentals shape: (1, 56)

In [47]:
for n in METADATA_COLS:
    print(n)

ticker
symbol
longName
shortName
exchange
fullExchangeName
market
sector
sectorKey
sectorDisp
industry
industryKey
industryDisp
longBusinessSummary
fullTimeEmployees
companyOfficers
executiveTeam
address1
address2
city
zip
country
phone
fax
website
currency
financialCurrency
language
region
quoteType
typeDisp
messageBoardId
exchangeTimezoneName
exchangeTimezoneShortName
gmtOffSetMilliseconds

In [48]:
for n in MARKET_DATA_COLS:
    print(n)

currentPrice
previousClose
open
dayLow
dayHigh
regularMarketPreviousClose
regularMarketOpen
regularMarketDayLow
regularMarketDayHigh
regularMarketPrice
regularMarketChange
regularMarketChangePercent
volume
regularMarketVolume
averageVolume
averageVolume10days
averageDailyVolume10Day
averageDailyVolume3Month
bid
ask
bidSize
askSize
marketState
regularMarketTime
fiftyTwoWeekLow
fiftyTwoWeekHigh
allTimeHigh
allTimeLow
fiftyDayAverage
twoHundredDayAverage
52WeekChange
SandP52WeekChange
fiftyTwoWeekLowChange
fiftyTwoWeekLowChangePercent
fiftyTwoWeekRange
fiftyTwoWeekHighChange
fiftyTwoWeekHighChangePercent
fiftyTwoWeekChangePercent
fiftyDayAverageChange
fiftyDayAverageChangePercent
twoHundredDayAverageChange
twoHundredDayAverageChangePercent
tradeable
triggerable
cryptoTradeable
hasPrePostMarketData
firstTradeDateMilliseconds
regularMarketDayRange

In [49]:
for n in FUNDAMENTAL_COLS:
    print(n)

marketCap
nonDilutedMarketCap
enterpriseValue
profitMargins
floatShares
sharesOutstanding
impliedSharesOutstanding
bookValue
priceToBook
trailingPE
forwardPE
priceToSalesTrailing12Months
netIncomeToCommon
trailingEps
forwardEps
pegRatio
trailingPegRatio
enterpriseToRevenue
enterpriseToEbitda
totalCash
totalCashPerShare
ebitda
totalDebt
quickRatio
currentRatio
totalRevenue
revenuePerShare
returnOnAssets
returnOnEquity
grossProfits
freeCashflow
operatingCashflow
earningsGrowth
revenueGrowth
grossMargins
ebitdaMargins
operatingMargins
epsTrailingTwelveMonths
epsForward
epsCurrentYear
priceEpsCurrentYear
heldPercentInsiders
heldPercentInstitutions
lastFiscalYearEnd
nextFiscalYearEnd
mostRecentQuarter
dividendRate
dividendYield
exDividendDate
payoutRatio
fiveYearAvgDividendYield
trailingAnnualDividendRate
trailingAnnualDividendYield
lastDividendValue
lastDividendDate
corporateActions

In [50]:
for n in ANALYST_COLS:
    print(n)

targetHighPrice
targetLowPrice
targetMeanPrice
targetMedianPrice
recommendationMean
recommendationKey
numberOfAnalystOpinions
averageAnalystRating
earningsTimestampStart
earningsTimestampEnd
isEarningsDateEstimate

# Price Data

In [6]:
sample_stockss = " ".join(all_tickers["Kode Jakarta"].tolist()[:3])
sample_stockss

'AALI.JK ABBA.JK ABDA.JK'

In [7]:
yfinance = yf.Tickers(sample_stockss)
price_data = yfinance.history(period="1y")

[*********************100%***********************]  3 of 3 completed

In [8]:
price_data.head()

Price             Close                 Dividends                  \
Ticker          AALI.JK ABBA.JK ABDA.JK   AALI.JK ABBA.JK ABDA.JK
Date
2025-07-10  5527.028809    37.0  3400.0       0.0     0.0     0.0
2025-07-11  5597.888672    37.0  3400.0       0.0     0.0     0.0
2025-07-14  5597.888672    37.0  3400.0       0.0     0.0     0.0
2025-07-15  5550.648926    37.0  3400.0       0.0     0.0     0.0
2025-07-16  5621.508301    37.0  3400.0       0.0     0.0     0.0

Price              High                          Low  ...          \
Ticker          AALI.JK ABBA.JK ABDA.JK      AALI.JK  ... ABDA.JK
Date                                                  ...
2025-07-10  5574.268371    37.0  3400.0  5456.169465  ...  3400.0
2025-07-11  5597.888672    37.0  3400.0  5527.029322  ...  3400.0
2025-07-14  5621.508455    37.0  3400.0  5527.029322  ...  3400.0
2025-07-15  5621.508274    37.0  3400.0  5527.029143  ...  3400.0
2025-07-16  5668.747866    37.0  3400.0  5574.268735  ...  3400.0

Price              Open                 Stock Splits                  Volume  \
Ticker          AALI.JK ABBA.JK ABDA.JK      AALI.JK ABBA.JK ABDA.JK AALI.JK
Date
2025-07-10  5527.028809    37.0  3400.0          0.0     0.0     0.0  322300
2025-07-11  5527.029322    37.0  3400.0          0.0     0.0     0.0  383700
2025-07-14  5597.888672    37.0  3400.0          0.0     0.0     0.0  597500
2025-07-15  5597.888491    37.0  3400.0          0.0     0.0     0.0  310300
2025-07-16  5574.268735    37.0  3400.0          0.0     0.0     0.0  610700

Price
Ticker        ABBA.JK ABDA.JK
Date
2025-07-10  1619800.0       0
2025-07-11  1735700.0       0
2025-07-14  1754400.0    1000
2025-07-15  1139000.0       0
2025-07-16  1096100.0       0

[5 rows x 21 columns]

In [15]:
df_flat = price_data.stack(level=1).rename_axis(['Date', 'Ticker']).reset_index()

# Check the new structure
display(df_flat.head(50))

C:\Users\zakis\AppData\Local\Temp\ipykernel_37592\1972877310.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_flat = price_data.stack(level=1).rename_axis(['Date', 'Ticker']).reset_index()

Price,Date,Ticker,Close,Dividends,High,Low,Open,Stock Splits,Volume
0,2025-07-10,AALI.JK,5527.028809,0.0,5574.268371,5456.169465,5527.028809,0.0,322300.0
1,2025-07-10,ABBA.JK,37.000000,0.0,37.000000,37.000000,37.000000,0.0,1619800.0
2,2025-07-10,ABDA.JK,3400.000000,0.0,3400.000000,3400.000000,3400.000000,0.0,0.0
3,2025-07-11,AALI.JK,5597.888672,0.0,5597.888672,5527.029322,5527.029322,0.0,383700.0
4,2025-07-11,ABBA.JK,37.000000,0.0,37.000000,37.000000,37.000000,0.0,1735700.0
5,2025-07-11,ABDA.JK,3400.000000,0.0,3400.000000,3400.000000,3400.000000,0.0,0.0
6,2025-07-14,AALI.JK,5597.888672,0.0,5621.508455,5527.029322,5597.888672,0.0,597500.0
7,2025-07-14,ABBA.JK,37.000000,0.0,37.000000,37.000000,37.000000,0.0,1754400.0
8,2025-07-14,ABDA.JK,3400.000000,0.0,3400.000000,3400.000000,3400.000000,0.0,1000.0
9,2025-07-15,AALI.JK,5550.648926,0.0,5621.508274,5527.029143,5597.888491,0.0,310300.0
10,2025-07-15,ABBA.JK,37.000000,0.0,37.000000,37.000000,37.000000,0.0,1139000.0
11,2025-07-15,ABDA.JK,3400.000000,0.0,3400.000000,3400.000000,3400.000000,0.0,0.0
12,2025-07-16,AALI.JK,5621.508301,0.0,5668.747866,5574.268735,5574.268735,0.0,610700.0
13,2025-07-16,ABBA.JK,37.000000,0.0,37.000000,37.000000,37.000000,0.0,1096100.0
14,2025-07-16,ABDA.JK,3400.000000,0.0,3400.000000,3400.000000,3400.000000,0.0,0.0
15,2025-07-17,AALI.JK,5999.424805,0.0,6046.664370,5668.747847,5668.747847,0.0,3101100.0
16,2025-07-17,ABBA.JK,38.000000,0.0,38.000000,37.000000,37.000000,0.0,491700.0
17,2025-07-17,ABDA.JK,3400.000000,0.0,3400.000000,3400.000000,3400.000000,0.0,0.0
18,2025-07-18,AALI.JK,5975.805176,0.0,6164.763442,5928.565609,6023.044742,0.0,2660000.0
19,2025-07-18,ABBA.JK,37.000000,0.0,37.000000,37.000000,37.000000,0.0,2743600.0
20,2025-07-18,ABDA.JK,3400.000000,0.0,3400.000000,3400.000000,3400.000000,0.0,0.0
21,2025-07-21,AALI.JK,6023.044434,0.0,6046.664216,5904.945523,5975.804869,0.0,993700.0
22,2025-07-21,ABBA.JK,38.000000,0.0,38.000000,37.000000,38.000000,0.0,2248500.0
23,2025-07-21,ABDA.JK,3400.000000,0.0,3400.000000,3400.000000,3400.000000,0.0,0.0
24,2025-07-22,AALI.JK,5928.565430,0.0,6093.903908,5904.945647,6046.664343,0.0,1238600.0
25,2025-07-22,ABBA.JK,37.000000,0.0,37.000000,37.000000,37.000000,0.0,2369000.0
26,2025-07-22,ABDA.JK,3400.000000,0.0,3400.000000,3400.000000,3400.000000,0.0,0.0
27,2025-07-23,AALI.JK,5975.805176,0.0,5999.424959,5904.945826,5928.565609,0.0,906200.0
28,2025-07-23,ABBA.JK,37.000000,0.0,37.000000,37.000000,37.000000,0.0,2952000.0
29,2025-07-23,ABDA.JK,3400.000000,0.0,3400.000000,3400.000000,3400.000000,0.0,0.0
30,2025-07-24,AALI.JK,6164.763184,0.0,6306.481877,5975.804925,5975.804925,0.0,2863900.0
31,2025-07-24,ABBA.JK,37.000000,0.0,37.000000,37.000000,37.000000,0.0,2005700.0
32,2025-07-24,ABDA.JK,3400.000000,0.0,3400.000000,3400.000000,3400.000000,0.0,0.0
33,2025-07-25,AALI.JK,6093.903809,0.0,6259.242284,6070.284026,6164.763155,0.0,1191600.0
34,2025-07-25,ABBA.JK,37.000000,0.0,37.000000,37.000000,37.000000,0.0,441000.0
35,2025-07-25,ABDA.JK,3400.000000,0.0,3400.000000,3400.000000,3400.000000,0.0,0.0
36,2025-07-28,AALI.JK,6141.143555,0.0,6141.143555,6046.664423,6046.664423,0.0,657900.0
37,2025-07-28,ABBA.JK,37.000000,0.0,38.000000,37.000000,37.000000,0.0,3367800.0
38,2025-07-28,ABDA.JK,3400.000000,0.0,3400.000000,3400.000000,3400.000000,0.0,0.0
39,2025-07-29,AALI.JK,6141.143555,0.0,6188.383120,6117.523772,6141.143555,0.0,684000.0
40,2025-07-29,ABBA.JK,36.000000,0.0,36.000000,36.000000,36.000000,0.0,1760300.0
41,2025-07-29,ABDA.JK,3400.000000,0.0,3400.000000,3400.000000,3400.000000,0.0,0.0
42,2025-07-30,AALI.JK,6542.680176,0.0,6566.299960,6212.003199,6259.242767,0.0,5501700.0
43,2025-07-30,ABBA.JK,36.000000,0.0,37.000000,36.000000,36.000000,0.0,75000.0
44,2025-07-30,ABDA.JK,3400.000000,0.0,3400.000000,3400.000000,3400.000000,0.0,0.0
45,2025-07-31,AALI.JK,6424.580566,0.0,6755.257507,6353.721222,6566.299255,0.0,5354200.0
46,2025-07-31,ABBA.JK,37.000000,0.0,37.000000,36.000000,36.000000,0.0,51900.0
47,2025-07-31,ABDA.JK,3400.000000,0.0,3400.000000,3400.000000,3400.000000,0.0,0.0
48,2025-08-01,AALI.JK,6424.580566,0.0,6495.439911,6330.101440,6471.820129,0.0,1105000.0
49,2025-08-01,ABBA.JK,36.000000,0.0,37.000000,36.000000,37.000000,0.0,86600.0

# Actions

In [ ]:
actions_all = pd.DataFrame()
for symbol, ticker in yfinance.tickers.items():
    actions = pd.DataFrame(ticker.actions)
    actions["symbol"] = symbol

    actions_all = pd.concat([actions_all, actions])

In [25]:
display(actions_all)

                            Dividends  Stock Splits   symbol
Date
2001-06-08 00:00:00+07:00    6.669957           0.0  AALI.JK
2002-06-19 00:00:00+07:00    9.528510           0.0  AALI.JK
2003-06-06 00:00:00+07:00   57.171062           0.0  AALI.JK
2004-06-07 00:00:00+07:00   85.756590           0.0  AALI.JK
2004-12-07 00:00:00+07:00   95.285100           0.0  AALI.JK
...                               ...           ...      ...
2018-05-02 00:00:00+07:00   90.000000           0.0  ABDA.JK
2019-06-10 00:00:00+07:00  190.000000           0.0  ABDA.JK
2020-08-04 00:00:00+07:00   60.000000           0.0  ABDA.JK
2021-06-17 00:00:00+07:00   67.000000           0.0  ABDA.JK
2022-06-07 00:00:00+07:00   81.506850           0.0  ABDA.JK

[61 rows x 3 columns]

In [26]:
actions_all.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 61 entries, 2001-06-08 00:00:00+07:00 to 2022-06-07 00:00:00+07:00
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Dividends     61 non-null     float64
 1   Stock Splits  61 non-null     float64
 2   symbol        61 non-null     object
dtypes: float64(2), object(1)
memory usage: 1.9+ KB

# Capital Gain

In [34]:
shares_full = pd.DataFrame()
for symbol, ticker in yfinance.tickers.items():
    sf = pd.DataFrame(ticker.get_shares_full())
    sf["symbol"] = symbol
    sf.rename(columns={0: "shares_outstanding"}, inplace=True)

    shares_full = pd.concat([shares_full, sf])

c:\Users\zakis\AppData\Local\pypoetry\Cache\virtualenvs\idx-portfolio-pipeline-zH2gfYpp-py3.13\Lib\site-packages\yfinance\base.py:617: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`).Please use a specific unit instead.
  start = end - pd.Timedelta(days=548)  # 18 months
c:\Users\zakis\AppData\Local\pypoetry\Cache\virtualenvs\idx-portfolio-pipeline-zH2gfYpp-py3.13\Lib\site-packages\yfinance\base.py:617: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`).Please use a specific unit instead.
  start = end - pd.Timedelta(days=548)  # 18 months
c:\Users\zakis\AppData\Local\pypoetry\Cache\virtualenvs\idx-portfolio-pipeline-zH2gfYpp-py3.13\Lib\site-packages\yfinance\base.py:617: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`).Please use a specific unit instead.
  start = end - pd.Timedelta(days=548)  # 18 months

In [35]:
display(shares_full)

                           shares_outstanding   symbol
2025-01-10 00:00:00+07:00          1940930048  AALI.JK
2025-01-11 00:00:00+07:00          1924690048  AALI.JK
2025-01-31 00:00:00+07:00          1932880000  AALI.JK
2025-02-01 00:00:00+07:00          1924690048  AALI.JK
2025-02-03 00:00:00+07:00          1932909952  AALI.JK
...                                       ...      ...
2025-11-14 00:00:00+07:00          4003753079  ABBA.JK
2025-11-17 00:00:00+07:00          3935892857  ABBA.JK
2025-09-18 00:00:00+07:00           620806680  ABDA.JK
2025-10-28 00:00:00+07:00           657182071  ABDA.JK
2025-10-29 00:00:00+07:00           620806680  ABDA.JK

[107 rows x 2 columns]

In [36]:
shares_full.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 107 entries, 2025-01-10 00:00:00+07:00 to 2025-10-29 00:00:00+07:00
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   shares_outstanding  107 non-null    int64
 1   symbol              107 non-null    object
dtypes: int64(1), object(1)
memory usage: 2.5+ KB